### ISSUE TITLE
CANNOT MAKE:  Version check is... wrong.

### ISSUE THREAD

**Issue by jamie-at-sas** [openshift/oc#1266]
```
jamie:~/git/openshift/oc$ git log -1
commit a6ac61e4a4ca576c48db33fe66f2be8c9086d50c (HEAD -> master, origin/release-4.13, origin/release-4.12, origin/master, origin/HEAD)
Merge: e4aa6edae 331b4b2da
Author: Justin Pierce <jupierce@redhat.com>
Date:   Thu Oct 13 16:28:04 2022 -0400

    Merge pull request #1264 from dcbw/dont-print-when-extracting

    pkg/cli/admin/release/extract: Don't print image metadata verification messages when extracting to stdout
jamie:~/git/openshift/oc$ make oc
/bin/sh: 1: set: Illegal option -o pipefail
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.15.2", detected version "1.19.2". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`.  Stop.
jamie:~/git/openshift/oc$
```
As you can see, I pulled the latest source, and tried to do `make oc` as it says in the README, but the version check is... wrong.

`GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
`GNU Make 4.3`
`Ubuntu 22.04 LTS`

**Comment by Otterian** [comment]
It seems that this PR https://github.com/openshift/oc/pull/1094 was aimed at fixing this issue (but went unnoticed by the maintainers) alternatively you can also just do
```make SHELL:=/bin/bash build```
In order to force make to use BASH. Same goes for other shells (fish/zsh) - YMMV on whether or not the shell of your choosing is compatible with the Makefile in question.
